import SwiftUI

struct LegalTextView: View {
    let title: LocalizedStringKey
    let text: String
    let onBack: () -> Void

    var body: some View {
        ZStack(alignment: .top) {
            Pigment.background.ignoresSafeArea()

            VStack(spacing: 0) {
                header
                ScrollView(showsIndicators: false) {
                    Text(text)
                        .font(Lettering.body(14))
                        .foregroundStyle(Pigment.cream.opacity(0.7))
                        .lineSpacing(5)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.top, 20)
                        .padding(.bottom, 40)
                }
            }
            .padding(.horizontal, 20)
        }
        .toolbar(.hidden, for: .navigationBar)
    }

    private var header: some View {
        ZStack {
            Text(title)
                .font(Lettering.displayMedium(22))
                .foregroundStyle(Pigment.cream)
            HStack {
                Button(action: onBack) {
                    Image(systemName: "arrow.left")
                        .font(.system(size: 16, weight: .medium))
                        .foregroundStyle(Pigment.cream)
                        .frame(width: Cadence.tapTarget, height: Cadence.tapTarget)
                        .background(Circle().fill(Pigment.surface))
                }
                .buttonStyle(.plain)
                Spacer()
            }
        }
        .padding(.top, 4)
    }
}

enum LegalCopy {
    static let privacyPolicy = """
    OracleBrew respects your privacy.

    What we collect: your profile details (name, birth date, and preferences you choose to share during onboarding), the photos you upload for a reading, and your reading and chat history. Everything currently lives on your device only — OracleBrew v1.0 has no backend server and does not transmit your data anywhere.

    Camera & Photos: we ask for camera access to let you photograph your cup, and photo library access to save your reading results. You can revoke either at any time in iOS Settings.

    What we don't do: we don't sell your data, run ads, or share anything with third parties. There is no analytics or tracking in this version of the app.

    This policy will be updated as OracleBrew adds cloud sync and account features in a future release.
    """

    static let termsOfUse = """
    Welcome to OracleBrew.

    OracleBrew provides fortune-telling content — coffee-ground readings and oracle chat — for entertainment purposes only. Nothing in the app constitutes professional advice of any kind (financial, medical, legal, or otherwise), and predictions should not be relied upon for real-world decisions.

    Age: you should be 13 or older to use OracleBrew.

    Content: all fortune tellers, readings, and chat replies are generated by the app for entertainment. Reading results are personal to your device and not shared with other users.

    Availability: features are provided as-is during this early version and may change without notice as the app evolves.

    By using OracleBrew, you agree to use it respectfully and for its intended entertainment purpose.
    """
}
